### PR TITLE
Fix CI & test Excel loading

### PR DESCRIPTION
**Pull request by mrakitin**
This can address #10 via CI, so we don't have this problem in the future.

### CODE REVIEW

**Comment by mrakitin** [comment]
I think this is a good test, and fails on loading the example file `examples/sample_list.xlsx` as expected: https://dev.azure.com/nsls2/profile_collections/_build/results?buildId=1522&view=logs&j=c58b40dd-1ba0-5a8c-8e7a-987c20afdefa&t=93432b4a-4194-569e-789f-66bf0407f74d.

**Comment by mrakitin** [comment]
This is not a fix (yet), but a verification that we have a problem with the new version of the `xlrd` package (v2.0.1).

**Comment by mrakitin** [comment]
I validated it manually, so we have done it at least once:
```py
$  ipython
Python 3.9.1 (default, Dec 11 2020, 06:28:49)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.20.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: K_LINE = ['Li_K', 'Be_K', 'B_K',  'C_K',  'N_K', 'O_K', 'F_K', 'Ne_K',
   ...:           'Na_K', 'Mg_K', 'Al_K', 'Si_K', 'P_K', 'S_K', 'Cl_K', 'Ar_K', 'K_K',
   ...:           'Ca_K', 'Sc_K', 'Ti_K', 'V_K', 'Cr_K', 'Mn_K', 'Fe_K', 'Co_K',
   ...:           'Ni_K', 'Cu_K', 'Zn_K', 'Ga_K', 'Ge_K', 'As_K', 'Se_K', 'Br_K',
   ...:           'Kr_K', 'Rb_K', 'Sr_K', 'Y_K', 'Zr_K', 'Nb_K', 'Mo_K', 'Tc_K',
   ...:           'Ru_K', 'Rh_K', 'Pd_K', 'Ag_K', 'Cd_K', 'In_K', 'Sn_K', 'Sb_K',
   ...:           'Te_K', 'I_K']
   ...:
   ...: L_LINE = ['Ga_L', 'Ge_L', 'As_L', 'Se_L', 'Br_L', 'Kr_L', 'Rb_L', 'Sr_L',
   ...:           'Y_L', 'Zr_L', 'Nb_L', 'Mo_L', 'Tc_L', 'Ru_L', 'Rh_L', 'Pd_L',
   ...:           'Ag_L', 'Cd_L', 'In_L', 'Sn_L', 'Sb_L', 'Te_L', 'I_L', 'Xe_L',
   ...:           'Cs_L', 'Ba_L', 'La_L', 'Ce_L', 'Pr_L', 'Nd_L', 'Pm_L', 'Sm_L',
   ...:           'Eu_L', 'Gd_L', 'Tb_L', 'Dy_L', 'Ho_L', 'Er_L', 'Tm_L', 'Yb_L',
   ...:           'Lu_L', 'Hf_L', 'Ta_L', 'W_L', 'Re_L', 'Os_L', 'Ir_L', 'Pt_L',
   ...:           'Au_L', 'Hg_L', 'Tl_L', 'Pb_L', 'Bi_L', 'Po_L', 'At_L', 'Rn_L',
   ...:           'Fr_L', 'Ac_L', 'Th_L', 'Pa_L', 'U_L', 'Np_L', 'Pu_L', 'Am_L']
   ...:
   ...: M_LINE = ['Hf_M', 'Ta_M', 'W_M', 'Re_M', 'Os_M', 'Ir_M', 'Pt_M', 'Au_M',
   ...:           'Hg_M', 'Tl_M', 'Pb_M', 'Bi_M', 'Sm_M', 'Eu_M', 'Gd_M', 'Tb_M',
   ...:           'Dy_M', 'Ho_M', 'Er_M', 'Tm_M', 'Yb_M', 'Lu_M', 'Th_M', 'Pa_M',
   ...:           'U_M']

In [2]: import periodictable

In [3]: validated = []
   ...: for el in K_LINE + L_LINE + M_LINE:
   ...:     el_obj = getattr(periodictable, el.split('_')[0])
   ...:     validated.append(el_obj)
   ...: print(validated)
[Li, Be, B, C, N, O, F, Ne, Na, Mg, Al, Si, P, S, Cl, Ar, K, Ca, Sc, Ti, V, Cr, Mn, Fe, Co, Ni, Cu, Zn, Ga, Ge, As, Se, Br, Kr, Rb, Sr, Y, Zr, Nb, Mo, Tc, Ru, Rh, Pd, Ag, Cd, In, Sn, Sb, Te, I, Ga, Ge, As, Se, Br, Kr, Rb, Sr, Y, Zr, Nb, Mo, Tc, Ru, Rh, Pd, Ag, Cd, In, Sn, Sb, Te, I, Xe, Cs, Ba, La, Ce, Pr, Nd, Pm, Sm, Eu, Gd, Tb, Dy, Ho, Er, Tm, Yb, Lu, Hf, Ta, W, Re, Os, Ir, Pt, Au, Hg, Tl, Pb, Bi, Po, At, Rn, Fr, Ac, Th, Pa, U, Np, Pu, Am, Hf, Ta, W, Re, Os, Ir, Pt, Au, Hg, Tl, Pb, Bi, Sm, Eu, Gd, Tb, Dy, Ho, Er, Tm, Yb, Lu, Th, Pa, U]
```

**Comment by mrakitin** [comment]
@irawaluyo, my latest commit https://github.com/NSLS-II-IOS/profile_collection/pull/11/commits/c4b924a2a9bc81f8e57f49f177f79608412ec0b8 downgraded `xlrd` to v1.2.0, and loading of the Excel file worked. Do you want me to downgrade the package on the IOS workstations?

**Comment by mrakitin** [comment]
Alright, that's what I've figured out:
- the version 2.0.0 of `xlrd`, released on 2020-12-11, removed support of any formats except `.xls` (see https://github.com/python-excel/xlrd/blob/master/CHANGELOG.rst#200-11-december-2020 for more details), so that the newer `.xlsx` or any other files won't be read;
- the recommended package to read `.xlsx` files is https://openpyxl.readthedocs.io;
- pandas v1.2.0 from 2020-12-26 was released with [the warning](https://pandas.pydata.org/pandas-docs/version/1.2.0/whatsnew/v1.2.0.html#what-s-new-in-1-2-0-december-26-2020) that `xlrd` and `xlwt` should not be used, and a better handling of the `.xlsx` files via `openpyxl`; however, it only became available in the [`defaults` channel](https://anaconda.org/anaconda/pandas/files) on 2021-01-07, after we generated the `collection-2021-1.0` conda environment on 2020-12-31;
- the `openpyxl` package is in the `collection-2021-1.0` conda environment, but pandas 1.1.5  did not have the proper processing to use `openpyxl` if it's installed.

Our options are:
1) Use `.xls` old-style files (MS Excel can save in that format), but it requires users/BL staff to reformat the files.
2) Downgrade `xlrd` package to v1.2, so that reading of `.xlsx` files is still possible.
3) Upgrade pandas (I think it's rather a bigger deal and has to happen in the next deployment).

I am inclined to (2), as it won't require any actions on the user side, and it's easier from the installation perspective.

**Comment by tacaswell** [comment]
> I am inclined to (2), as it won't require any actions on the user side, and it's easier from the installation perspective.

I agree.

**Comment by mrakitin** [comment]
Thanks @tacaswell! The [fix](https://github.com/NSLS-II/playbooks/pull/436) has been pushed to IOS (and XFP) already. We need to push it to other beamlines which read Excel files for DAQ.

**Pull request merged**
